version: '2'
services:
  eureka:
    build: ./Eureka
    ports:
      - "8761:8761"
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"