server:
  port: 8762

spring:
  application:
    name: zuul-gtw

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  routes:
    payment:
      path: /api/orders/*/payment
    orders:
      path: /api/orders/**
    warehouse:
      path: /api/warehouse/**