server:
  port: 8762

spring:
  application:
    name: zuul-gtw

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

zuul:
  routes:
    payment1:
      path: /api/orders/*/payment
      serviceId: payment
    payment2:
      path: /api/payment/**
      serviceId: payment
    orders:
      path: /api/orders/**
      serviceId: orders
    warehouse:
      path: /api/warehouse/**
      serviceId: warehouse

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000