server:
  port: 8081

spring:
  application:
    name: warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/MCA.warehouse
    username: postgres
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka